spring.application.name=w1crud_maven



server.port=6969
spring.datasource.url=jdbc:postgresql://localhost:5432/hsf302
spring.datasource.username=postgres
spring.datasource.password=25251325
spring.datasource.driver-class-name=org.postgresql.Driver

#never use ddl-auto in production!
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
#Those lines to let liquibase use a different Database compare to main application
#spring.liquibase.url=jdbc:postgresql://localhost:5432/hsf302
#spring.liquibase.user=postgres
#spring.liquibase.password=25251325
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.default-schema=public


# Data Serialization Mode
spring.data.web.pageable.serialization-mode=via_dto

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:6969
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true 
# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.csrf.enabled=false
DURATION:900
REFRESH_DURATION:2
jwt:aa1d11d3cf852fe2ed8e44dcdb3c78721b0aefa74d2e05493858a78f805e4a53

rsa.key.private:MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDAuorl2DVW9IneftCZNdB0/7Jnpv6N+T/TlrTMJ8w0g/7egJcMuXl2c3USk6zCNSzJkxiRtUwbFvx2QfKAD4iktbr5GowFaQ4t7V1ZXiwX47HjhTZN4kRqLDuNiD+oLYl5qLtboATUsTCO04q45eYoEx1OPvK40iJGr9YQuMQu9A56NufiutB2+AVJXE/wDSJiiTHFmyvlYQOzZN39wpfJfou8397olxXZFigauo+v5Ysc87CtvXlQMK2SZJX8BFDhsLHxeXMT3ZIJmOZp3cNEWk+hvq2a4I1Z7kCplZD+KKl+8qBcpxUKgfeYFKWaIPCrilEV5tjAAnZbQ4O57YRLAgMBAAECggEAC3iO39NDNCO7OPpEoXnUfcI3n3e5sEA6OPZqrbleAW+Bx0MmumPSWOcnpq1ncOpdT2S+kkg/eV/1iCGwtJ04EtBGNUwL3XPn8M/Z6IHJug+b/OC8NLKCQ+zSC+skxCEXDPNVWMS+GjKu+Iaau8U4h6trk8anXQdqHC7xshkX2Xt5bBfeW9K2yGWGUp0l+5S1fk9lH2/tFjou2Px2gpTJbe6iNGTL0Z2Mo9FP9owCBQq09sTpDYaXwTjCCJgAzTNO2ZuwQ3CSaMsh9+ZkjQYT+IuRkotx/eA3eeTO/L03Ex9v8xoqbDwesFJCQKiHt/dEeUnqZs3evFj+1f2N1PnWMQKBgQDirkCmAQIIXUee4kA4NiZ4g948Tx9oZtJrCyL7CrRVeEEr74X7OAzrCc+DdIcpFEGSH7Ytzu9acaidfvqAcUEaGiHQspLAlnZrx58a1GY80RKJYWQ5femCDhomRmLn5rQ+nT3yey2++SRTsE1u0n3/HP4bDEZzFfChp8EOZsj9XwKBgQDZqBZMfYAU26ur1HvUTGKW8f3+8keptrJQ3ngWB0WmYKMBAlB38TRk6WZVukkQsf6VypUSs8Z3nOlrNmofs4iJobhSlHiq9lK14B6xgGFdUz1PR2sWnQRYCDYNbCdtm9yy0f2loP1pBxvt1PTpTdmxmM3ceKeD7WE1gY/FW710lQKBgFsT4G3SodpygEBab6smNrbdZQGeWOQ9y/Wud9OeLW7Z7nWUu6SAlNArFPGgdF4RAXeQvkYRiyIv4KvHRScuWhX+we90kHpI+jO79TV2ec2dw3DnbLmc2aGjwOX4Ce1bSLiPvUAcNfkxaWMmxzXr5SwHniGIARZkjlalbHA45DDJAoGBAKgFujESMO3pJn1farhYv0MHTKyjG+9Huh/znYBj3MCzmSIOR1BQQ8Ii630CcaURwxafbLUjUvLDju3U89fFIIIe9cvKEdzoirEccpVUJdWFjK7G00SBsfjDXfa+pzFWQOlKciSKQxXxBv5yhx4Tmxoee8zW13pgpcpIWlRgncCBAoGBAI2QDqlkFDJXtCqpfhhcFvcsfwLcv3IRmEyI7v6am5JxDEnJGjsqxid0s6/VTVtCVuzPfmPr64SyEo1cUtImi9FwamF+87pqdi8bNSdnz2wzTKDsBS1eFzvX7Y0hxqRkBRKm6OTMERUwrivomkeDGy8aeRMFkpRZb6MQ4J9JNKbs
rsa.key.public:MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwLqK5dg1VvSJ3n7QmTXQdP+yZ6b+jfk/05a0zCfMNIP+3oCXDLl5dnN1EpOswjUsyZMYkbVMGxb8dkHygA+IpLW6+RqMBWkOLe1dWV4sF+Ox44U2TeJEaiw7jYg/qC2Jeai7W6AE1LEwjtOKuOXmKBMdTj7yuNIiRq/WELjELvQOejbn4rrQdvgFSVxP8A0iYokxxZsr5WEDs2Td/cKXyX6LvN/e6JcV2RYoGrqPr+WLHPOwrb15UDCtkmSV/ARQ4bCx8XlzE92SCZjmad3DRFpPob6tmuCNWe5AqZWQ/iipfvKgXKcVCoH3mBSlmiDwq4pRFebYwAJ2W0ODue2ESwIDAQAB
spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
logging.config=classpath:logback-spring.xml

#redis config

spring.data.redis.host=localhost
spring.data.redis.port=6379