spring.application.name=w1crud_maven



server.port=6969
spring.datasource.url=jdbc:postgresql://localhost:5432/hsf302
spring.datasource.username=postgres
spring.datasource.password=25251325
spring.datasource.driver-class-name=org.postgresql.Driver

#never use ddl-auto in production!
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Those lines to let liquibase use a different Database compare to main application
#spring.liquibase.url=jdbc:postgresql://localhost:5432/hsf302
#spring.liquibase.user=postgres
#spring.liquibase.password=25251325
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.default-schema=public


# Data Serialization Mode
spring.data.web.pageable.serialization-mode=via_dto

# CORS Configuration
spring.web.cors.allowed-origins=http://localhost:6969
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true 
# Swagger/OpenAPI Configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v1/api-docs
springdoc.swagger-ui.csrf.enabled=false

jwt:aa1d11d3cf852fe2ed8e44dcdb3c78721b0aefa74d2e05493858a78f805e4a53

spring.thymeleaf.cache=false 
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html